server:
  port: 8002


spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 542270191MSzyl
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 40000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: selcet 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true

eureka:
  client:
    fetch-registry: true # 自己是客户端，要检索服务
    register-with-eureka: true # false表示不向注册公司注册自己
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个网址
#  instance:
#    instance-id: payment8002
#    prefer-ip-address: true