server:
  port: 80

eureka:
  client:
    fetch-registry: true # 自己是客户端，要检索服务
    register-with-eureka: true # false表示不向注册公司注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个网址

spring:
  application:
    name: cloud-consumers-order